package ru.digital.hack.parent.controller;

import au.com.bytecode.opencsv.CSVReader;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import ru.digital.hack.parent.dao.ReviewsEntity;
import ru.digital.hack.parent.repo.ReviewsRepo;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import static org.springframework.web.bind.annotation.RequestMethod.GET;

@CrossOrigin(origins = "http://localhost:3000", maxAge = 3600)
@RestController
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ReviewsRepo reviewsRepo;


    @GetMapping("/test")
    public List<ReviewsEntity> mainPage(){
         List<ReviewsEntity> reviews = reviewsRepo.findAll();
        return reviews;
    }

    @RequestMapping(value = "/addCsv",
            method = GET)
    @ResponseBody
    public String addCsv() {
        List<String[]> entityList = new ArrayList<>();
        try {

            CSVReader reader = new CSVReader(new FileReader("C:\\Users\\Mihailo\\Downloads\\Telegram Desktop\\full_company_data.csv"), ',', '\'', 1);
            //Read CSV line by line and use the string array as you want
            entityList = reader.readAll();
     //       entityList.stream()
     //               .map((p) ->  new ReviewsEntity(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9], p[10], p[11], p[12], p[13], p[14]))
     //               .map((entity) -> reviewsRepo.save(entity))
     //               .count();
            return "susses";
        } catch (FileNotFoundException e) {
            return "fail";
        } catch (IOException e) {
            e.printStackTrace();
            return "fail";
        }
    }
}

